import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className={styles.grid}>
          <a href="iss-ssg" className={styles.card}>
            <h2>Statically generated page (SSG) &rarr;</h2>
            <p>
              Using <code className={styles.code}>getStaticProps</code>
            </p>
          </a>

          <a href="iss-ssr" className={styles.card}>
            <h2>Server-side rendered page (SSR) &rarr;</h2>
            <p>
              Using <code className={styles.code}>getServerSideProps</code>
            </p>
          </a>

          <a href="hello" className={styles.card}>
            <h2>Polling the own API &rarr;</h2>
            <p>
              From <code className={styles.code}>api/company</code>
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
